165 ubuntu vtk conflicts with paraview
MPS-Basic/MPS-Basic pull request #166
Opened 2024-11-08 14:33 UTC by Quesys-tech

VTKなしでバイナリVTKを出力する

2024-11-08 15:19 UTC, zukain5 commented on src/particles_exporter.cpp
> +}
これは実行環境によって変わるってことですか？

2024-11-09 07:48 UTC, Quesys-tech commented on src/particles_exporter.cpp
> +}
そうです。Armだとバイエンディアンでどっちになるかわからないのです

2024-11-09 10:59 UTC, Quesys-tech commented
ドキュメントへの反映がなかったのでやります

2024-11-09 13:09 UTC, zukain5 requested changes
コードはだいたい理解しました。
バイナリ形式での書き込みは結構低レイヤーでコード難しく、Basic 感がないのでオプションにしたほうがいいんじゃないかと思います（初心者が変更を加えるのが難しい）

2024-11-13 04:08 UTC, Quesys-tech commented
@zukain5 
CMake経由で`#ifdef`~`#endif`を有効/無効を切り替えて形式が変わるようにしますか？
関数を切り替えるというのも考えましたが、CMakeでオプションを一元管理したほうがよいと思います。

2024-11-13 04:18 UTC, zukain5 commented
> @zukain5 CMake経由で`#ifdef`~`#endif`を有効/無効を切り替えて形式が変わるようにしますか？ 関数を切り替えるというのも考えましたが、CMakeでオプションを一元管理したほうがよいと思います。

@Quesys-tech 
`#ifdef` を使う場合ってどんな感じになりますか・・？
あまり詳しくなく、イメージがつかないです。

2024-11-15 12:10 UTC, Quesys-tech commented
>#ifdef を使う場合ってどんな感じになりますか・・？
あまり詳しくなく、イメージがつかないです。

1. CMakeでコンパイラのオプションを設定する
2. コンパイラでプリプロセッサの定義がされる
3. `#ifdef`で定義されたものがコンパイルされる
という感じです。

https://nkshigeru.hatenablog.com/entry/2019/01/17/003029

2024-11-15 12:12 UTC, zukain5 commented
理解しました
関数を分けて設定ファイルに設定を集約した方がいいかなと思っていますが、どうでしょう

2024-11-15 12:23 UTC, Quesys-tech commented
@zukain5 

> 関数を分けて設定ファイルに設定を集約した方がいいかなと思っていますが、どうでしょう

たしかにそっちのほうがわかりやすいですね。
設定ファイルと初期粒子配置だけ保存しておけば再現可能になりますから。

2024-12-05 07:54 UTC, zukain5 requested changes

2024-12-05 08:17 UTC, Quesys-tech commented on input/dambreak/settings.yml
> +outputVtkFormat: binary # ascii or binary (if is not specified, ascii is used)
272fc1c74bb8ac1452861a6e9a0f3e14d43c59d6 で修正しました

2024-12-12 09:39 UTC, zukain5 approved these changes
OKです！

2024-12-12 09:41 UTC, merged