refactor: use uv instead of raw pip
MPS-Basic/MPS-Basic pull request #169
Opened 2024-11-09 12:04 UTC by Quesys-tech

2024-11-09 12:49 UTC, zukain5 requested changes
うーん、CI で使うだけなら、仮想環境入れるまでしたくない気持ちがあります・・・
（特に python については仮想環境の構築方法に好みがありますし・・・

2024-11-11 06:30 UTC, Quesys-tech commented
>仮想環境入れるまでしたくない気持ちがあります・・・

CIはほぼ書き捨てとはいえ、matplotlibとかはシステムのパッケージマネージャで管理されている場合が多いので生でインストールするのはあまり良いとは言えない状況になってます。

最近のPythonはシステム管理と仮想環境を厳格に分けるようになっていて、システム側にライブラリを入れるのが推奨されなくなっていいます。

Ubuntu 24.04ではpipで直接ライブラリを入れようとすると
```
pip install matplotlib --user
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```
とエラーが出ます。

>  python については仮想環境の構築方法に好みがありますし

現状で一番高速で使いやすいものではないかと考えています。
- pipenvやpoetoryはpythonランタイムのバージョン管理が単体でできないが弱点です。
- 依存関係のインストールが圧倒的に早くCIとの相性が良いです。

以上長文失礼しました。

2024-11-11 07:19 UTC, zukain5 commented
@Quesys-tech 
であれば、可視化をプロジェクトとしてサポートする形で、可視化スクリプトを仮想環境付きで scripts か違ったディレクトリに移し、CI ではそれを呼び出すのがいいかなあと思いました

2024-11-13 03:12 UTC, closed without merging

2024-11-13 03:12 UTC, Quesys-tech commented
全体でPythonを入れるという話があったので一旦取り下げます