Introduce EMPS
MPS-Basic/MPS-Basic pull request #45
Opened 2024-02-23 11:35 UTC by iori3150

2024-02-23 11:49 UTC, zukain5 commented
Merge #41 before merge this

2024-02-23 12:33 UTC, Quesys-tech reviewed
#41 のあとにもう一度見ます

2024-02-23 14:26 UTC, zukain5 commented
なんか差分でかいな？

2024-02-23 14:38 UTC, zukain5 commented
できたできた

@iori3150 すみませんが、歴史改変したのでローカルで以下のコマンドを実行してください

```
git switch 12-high-precision-mps
git reset --hard origin/12-high-precision-mps
```

2024-02-23 14:40 UTC, zukain5 commented on src/pressure_calculator/explicit.cpp
> +	this->soundSpeed   = soundSpeed;
こっちも speedOfSound にしときますかー

2024-02-23 14:41 UTC, zukain5 commented on input/dambreak/settings.yml
> +outputDirectory: ../../result/explicit
ここはもとのままのがいいかもです

2024-02-23 14:42 UTC, zukain5 commented on src/mps.cpp
> +	if (auto explicitPressureCalculator = dynamic_cast<PressureCalculator::Explicit*>(pressureCalculator.get())) {
この if ほんとに Explicit のときだけしか機能しないのかな？（Copilot コードなのでちょっと疑心）

2024-02-23 14:45 UTC, zukain5 requested changes
若干修正すれば概ね良さそうです！

2024-02-24 07:22 UTC, iori3150 commented on src/pressure_calculator/explicit.cpp
> +	this->soundSpeed   = soundSpeed;
修正した！

2024-02-24 07:22 UTC, iori3150 commented on input/dambreak/settings.yml
> +outputDirectory: ../../result/explicit
修正した！

2024-02-24 07:23 UTC, iori3150 commented on src/mps.cpp
> +	if (auto explicitPressureCalculator = dynamic_cast<PressureCalculator::Explicit*>(pressureCalculator.get())) {
よく分からないのでほっておいてある！

2024-02-24 07:23 UTC, iori3150 commented
@Quesys-tech 
確認お願いしますー！

2024-02-24 07:28 UTC, iori3150 commented on input/dambreak/settings.yml
> +speedOfSound: 17.1
あ！srcしか見てなかった
ありがとう！

2024-02-24 08:52 UTC, iori3150 commented on src/simulation.cpp
> +	if (input.settings.pressureCalculationMethod == "Implicit") {
ここです！

2024-02-24 09:33 UTC, iori3150 commented on src/simulation.cpp
> +	if (input.settings.pressureCalculationMethod == "Implicit") {
@Quesys-tech

2024-02-25 03:54 UTC, Quesys-tech commented on src/simulation.cpp
> +	if (input.settings.pressureCalculationMethod == "Implicit") {
ありがとうございます

2024-02-25 04:02 UTC, zukain5 approved these changes
LGTM!

2024-02-25 04:16 UTC, merged