68 自由表面判定 Based on Particle Distribution
MPS-Basic/MPS-Basic pull request #71
Opened 2024-02-25 13:09 UTC by iori3150

本当はクラス化したいけどとりあえずPR

2024-02-25 13:17 UTC, Quesys-tech reviewed
手法の出典はどれでしょうか？

2024-02-25 13:39 UTC, iori3150 commented
> 手法の出典はどれでしょうか？

[Khayyer et al.(2009)](https://doi.org/10.1016/j.apor.2009.06.003)です．
後藤本のp.52から持ってきました．
（ドキュメントに追記予定です）

2024-02-25 13:48 UTC, zukain5 requested changes
いくつかコメント書きました！意見ありましたらお気軽にどうぞ！

2024-02-25 13:48 UTC, zukain5 commented on src/particles_exporter.cpp
> +void ParticlesExporter::toVtu(const fs::path& path, const double& time, const double& n0ForNumberDensity) {
これ、n0 は opptional にしたいきもち

2024-02-25 13:48 UTC, zukain5 commented on input/dambreak/settings.yml
> +surfaceDetection-numberDensity-threshold: 0.97 # threshold ratio of the number density
ハイフン混ぜずに全部 camelCase がいいな・・・

2024-02-25 13:48 UTC, zukain5 commented on src/mps.cpp
> +            if (isFreeSurface(pi)) {
いい関数定義です！知りすぎてないコード！

2024-02-25 13:50 UTC, iori3150 commented on input/dambreak/settings.yml
> +surfaceDetection-numberDensity-threshold: 0.97 # threshold ratio of the number density
えーなんか```surfaceDetection-手法-変数名```の命名規則にすると分かりやすいかなーと思って
全部camelだと長すぎてどこで区切られてるのかわかんないジャーン

2024-02-25 13:51 UTC, iori3150 commented on src/particles_exporter.cpp
> +void ParticlesExporter::toVtu(const fs::path& path, const double& time, const double& n0ForNumberDensity) {
そんなんできんだ！

2024-02-25 13:58 UTC, Quesys-tech commented on input/dambreak/settings.yml
> +surfaceDetection-numberDensity-threshold: 0.97 # threshold ratio of the number density
yamlは階層化できるので階層化したほうがよいと思います。

2024-02-25 13:59 UTC, zukain5 commented on src/particles_exporter.cpp
> +void ParticlesExporter::toVtu(const fs::path& path, const double& time, const double& n0ForNumberDensity) {
実現方法はわからないですｗさすがにあってほしいなあ

2024-02-25 14:07 UTC, iori3150 commented on input/dambreak/settings.yml
> +surfaceDetection-numberDensity-threshold: 0.97 # threshold ratio of the number density
そしたらとりあえずyamlは階層化します！

2024-02-25 14:07 UTC, Quesys-tech commented on src/particles_exporter.cpp
> +void ParticlesExporter::toVtu(const fs::path& path, const double& time, const double& n0ForNumberDensity) {
http://www.s-cradle.com/developer/sophiaframework/tutorial/Cpp/argdefault.html

2024-02-25 14:08 UTC, iori3150 commented on src/settings.hpp
> +    double surfaceDetection_numberDensity_threshold{}; ///< threshold ratio of number density for free surface detection
@zukain5 
こっちは許す？

2024-02-25 14:09 UTC, iori3150 commented
- [ ] yamlを階層化
- [ ] n0をopptionalに
- [ ] 内部の変数はアンダースコアで良い？

2024-02-25 14:21 UTC, zukain5 commented on src/settings.hpp
> +    double surfaceDetection_numberDensity_threshold{}; ///< threshold ratio of number density for free surface detection
こっちもやだあ

2024-02-25 14:23 UTC, iori3150 commented on src/settings.hpp
> +    double surfaceDetection_numberDensity_threshold{}; ///< threshold ratio of number density for free surface detection
なんでだよ！
分かりにくすぎるだろこんなの全部camelになってたら！

2024-02-25 14:24 UTC, iori3150 commented on src/settings.hpp
> +    double surfaceDetection_numberDensity_threshold{}; ///< threshold ratio of number density for free surface detection
後でクラス化したら解決されるから，今は修正面倒なのでこのままにします．

2024-02-25 14:39 UTC, zukain5 commented on src/settings.hpp
> +    double surfaceDetection_numberDensity_threshold{}; ///< threshold ratio of number density for free surface detection
たしかに

2024-02-25 14:41 UTC, zukain5 commented on src/settings.hpp
> +    double surfaceDetection_numberDensity_threshold{}; ///< threshold ratio of number density for free surface detection
> なんでだよ！
> 分かりにくすぎるだろこんなの全部camelになってたら！

camel とアンスコを同時に許すと悩んじゃうので機械的に決めれるようにしたいためです
そもそも長すぎる変数名が悪い！！

2024-02-25 21:09 UTC, Quesys-tech commented on input/dambreak/settings.yml
> +surfaceDetection-numberDensity-threshold: 0.97 # threshold ratio of the number density
破壊的変更かつ他への影響も大きいので別件で議論しましょう(#79 )。本PRはこれでよいです。

2024-02-25 21:36 UTC, Quesys-tech commented on src/particles_exporter.cpp
> -void ParticlesExporter::toVtu(const fs::path& path, const double& time) {
あと`time`が使われていないので[Field Data as Time Meta-Data in VTK XML File Formats - VTK documentation](https://docs.vtk.org/en/latest/design_documents/IOXMLTimeInFieldData.html#field-data-as-time-meta-data-in-vtk-xml-file-formats)を参考にVTKファイルにも時刻を書き込みませんか？

2024-02-25 21:38 UTC, Quesys-tech requested changes

2024-02-25 21:38 UTC, Quesys-tech commented on src/mps.hpp
> +    bool isParticleDistributionBiased(const Particle& pi);
出典を書きましょう。

2024-02-26 00:35 UTC, iori3150 commented on src/particles_exporter.cpp
> -void ParticlesExporter::toVtu(const fs::path& path, const double& time) {
それは是非やりたいですね！
このプルリクとは趣向が違うと思うので別のブランチ立ち上げますー

2024-02-26 00:41 UTC, iori3150 commented on src/particles_exporter.cpp
> -void ParticlesExporter::toVtu(const fs::path& path, const double& time) {
#80

2024-02-27 10:43 UTC, iori3150 commented
@zukain5 @Quesys-tech 
ご指摘修正したので確認お願いしますー！

2024-02-27 10:48 UTC, Quesys-tech reviewed
静水圧の計算直したらOKです！

2024-02-27 10:48 UTC, Quesys-tech commented on src/mps.hpp
> +    bool isParticleDistributionBiased(const Particle& pi);
ありがとうございます

2024-02-27 12:38 UTC, iori3150 commented
@Quesys-tech 
mainからマージしてきたらCIがビルドでコケてるんですが，どうしたらいいでしょうか？？
https://github.com/MPS-Basic/MPS-Basic/actions/runs/8064822509/job/22029456634?pr=71

2024-02-27 13:56 UTC, Quesys-tech commented
@iori3150 ローカルでEigenのサブモジュールを消してください
https://zenn.dev/miharun/articles/40210d8fa77478

2024-02-27 14:00 UTC, Quesys-tech approved these changes
静水圧もきちんと計算できてます。
承認します！

2024-02-27 14:16 UTC, iori3150 commented
ありがとうございますー！

2024-02-27 14:34 UTC, zukain5 approved these changes

2024-02-27 23:01 UTC, merged