74 upload figure after ci
MPS-Basic/MPS-Basic pull request #78
Opened 2024-02-25 19:30 UTC by iori3150

できたはず！！

2024-02-25 20:50 UTC, Quesys-tech commented on ci/upload_image.py
> +CLIENT_ID = "a0a98f5baed7b8f"
imgurに詳しくないのですが、client idというものはソースに書きこんで問題ないものなんでしょうか？

2024-02-25 20:50 UTC, Quesys-tech commented on .github/workflows/calc-hydrostatic.yml
> +          echo -e "Hydrostatic problem was calculated.\n <img src=https://i.imgur.com/b8wUvPv.png>" > ${{ steps.strings.outputs.pr-comment }}
リンクがハードコーディングされていませんか？

2024-02-26 00:10 UTC, zukain5 reviewed
写真を半永久的に上げ続けることになると思うんですが、容量とか大丈夫でしょうか？

2024-02-26 00:25 UTC, iori3150 commented on ci/upload_image.py
> +CLIENT_ID = "a0a98f5baed7b8f"
よろしくないですねーーー…
シークレットにします㊙️
https://zenn.dev/ameyo/articles/9bff066c0402d3

2024-02-26 00:33 UTC, iori3150 commented
> 写真を半永久的に上げ続けることになると思うんですが、容量とか大丈夫でしょうか？

容量制限ないらしい（すごい）
![7C3A182B-A6EC-46D4-9E5E-79CCB45032F0](https://github.com/MPS-Basic/MPS-Basic/assets/88538282/fd590088-a167-45e3-8f25-11906a3e2bb2)
https://help.imgur.com/hc/en-us/articles/115000083326-What-files-can-I-upload-Is-there-a-size-limit

2024-02-26 00:35 UTC, zukain5 commented on ci/upload_image.py
> +CLIENT_ID = "a0a98f5baed7b8f"
IDは公開してもいい気も？ただ伏せといてもいいですね

2024-02-26 00:39 UTC, iori3150 commented on ci/upload_image.py
> +CLIENT_ID = "a0a98f5baed7b8f"
このIDはどのアプリケーションが画像をアップロードしてるか見ていて、アップロードレイトリミットがあるので、超暇な悪者がいるとこのIDを使って画像アップロードしまくってレイトリミットを超えるってことは起こりうる

2024-02-26 00:44 UTC, zukain5 commented
1時間に50個の制限はあるみたいですね。
複数コミットを同時にpushした場合、CIの実行自体を最新コミットのみに制限することってできないんてすかね？

2024-02-26 01:04 UTC, zukain5 commented
すでにそうなってそう。さらに [skip ci] で CI が回らないようにすることもできるみたい。利用できそう

2024-02-26 02:25 UTC, zukain5 requested changes
@Quesys-tech の指摘を直せばOKです！

2024-02-26 02:29 UTC, iori3150 commented
- [ ] idをシークレット化
- [ ] リンクのハードコーディングを修正

2024-02-27 09:57 UTC, iori3150 commented
@zukain5 
修正したので確認後approveお願いしまーす

2024-02-27 10:07 UTC, zukain5 approved these changes

2024-02-27 10:22 UTC, merged