67 add explicit pressure calculation onto documentation
MPS-Basic/MPS-Basic pull request #99
Opened 2024-03-04 13:18 UTC by iori3150

2024-03-06 15:13 UTC, zukain5 requested changes
unique_ptr の話わかりやすかったです！
いくつかコメントしましたー

2024-03-06 15:13 UTC, zukain5 commented on docs/coding_techniques.md
> +```
前後に空行を入れてあげたほうが安全かもしれません（現に GitHub のシンタックスハイライトがバグっちゃってるので）

2024-03-06 15:13 UTC, zukain5 commented on docs/improved_algorithms/pressure_calculation.md
> +```yml
```suggestion
```yaml
```



これシンタックスハイライトが効いてなかったんですが、yaml のほうがいいのかな？

2024-03-06 15:13 UTC, zukain5 commented on docs/coding_techniques.md
> +by c++ rule.
recommend なんですかね？強制している説もあります（わからん）

2024-03-06 15:13 UTC, zukain5 commented on docs/coding_techniques.md
> +};
```suggestion
namespace PressureCalculator {
class Interface {
public:
    virtual std::vector<double> calc(const std::vector<Particle>& particles) = 0;

    virtual ~Interface(){};
};
}
```

一応、namespace で囲っておいてあげたほうがいいかもしれない

2024-03-06 15:13 UTC, zukain5 commented on docs/coding_techniques.md
> +`virtual ~Interface(){};` is a deconstructor.
```suggestion
`virtual ~Interface(){};` is a destructor.
```

2024-03-19 03:32 UTC, iori3150 commented on docs/improved_algorithms/pressure_calculation.md
> +```yml
（実はDoxygenはyaml対応してないので気持ちで入れてるだけ…）

2024-03-19 03:36 UTC, iori3150 commented on docs/coding_techniques.md
> +by c++ rule.
分からんから一旦飛ばす！笑

2024-03-19 03:40 UTC, merged